<!DOCTYPE html>
<html>

<head>
    <title>Service Order</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #333;
        }

        .header {
            width: 100%;
            border-bottom: 2px solid #f59e0b;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #f59e0b;
        }

        .title {
            text-align: right;
            float: right;
            font-size: 18px;
            font-weight: bold;
        }

        .section {
            margin-bottom: 20px;
        }

        .label {
            font-weight: bold;
            color: #555;
            width: 120px;
            display: inline-block;
        }

        .alert {
            background-color: #fff3cd;
            color: #856404;
            padding: 10px;
            border: 1px solid #ffeeba;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #888;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <span class="logo">Travel Agency - Partner</span>
        <span class="title">WORK ORDER / ORDEN DE SERVICIO</span>
        <div style="clear: both;"></div>
    </div>

    <div class="section">
        <div><span class="label">Ref:</span> <strong>{{ $item->reservation->booking_ref }}</strong></div>
        <div><span class="label">Date:</span> {{ $item->date->format('d M Y') }}</div>
    </div>

    <div class="section">
        <h3>Client / Passenger</h3>
        <div><span class="label">Name:</span> <strong style="font-size: 14px;">{{ $item->reservation->contact_name }}
                {{ $item->reservation->contact_surname }}</strong></div>
        <div><span class="label">Phone:</span> {{ $item->reservation->contact_phone }}</div>
        <div><span class="label">Pax:</span> <strong>{{ $item->pax }}</strong> (Units: {{ $item->units }})</div>
    </div>

    <div class="section">
        <h3>Service Logistics</h3>
        <table class="table">
            <tr>
                <th style="width: 30%;">Service</th>
                <td>{{ $item->service_name }} ({{ $item->zone_name }})</td>
            </tr>

            @if($item->airline || $item->arrival_flight_number)
                <tr>
                    <th>Arrival Flight</th>
                    <td>
                        <strong>{{ $item->airline }} {{ $item->arrival_flight_number }}</strong>
                        @if($item->arrival_time) @ {{ $item->arrival_time }} @endif
                        (Terminal: {{ $item->arrival_terminal }})
                    </td>
                </tr>
            @endif

            @if($item->departure_airline || $item->departure_flight_number)
                <tr>
                    <th>Departure Flight</th>
                    <td>
                        <strong>{{ $item->departure_airline }} {{ $item->departure_flight_number }}</strong>
                        @if($item->departure_time) @ {{ $item->departure_time }} @endif
                    </td>
                </tr>
            @endif

            @if($item->pickup_time)
                <tr style="background-color: #ecfeff;">
                    <th>PICKUP TIME</th>
                    <td style="font-size: 14px; font-weight: bold; color: #0e7490;">
                        {{ \Carbon\Carbon::parse($item->pickup_time)->format('H:i') }}</td>
                </tr>
            @endif
        </table>
    </div>

    <div class="section alert">
        <strong>Provider Note:</strong> Please ensure the vehicle is clean and driver is present 10 minutes before
        pickup time.
    </div>

    <div class="footer">
        Generated by Travel Agency System | Partner: {{ $item->assignedProvider->name ?? 'Pending' }}
    </div>
</body>

</html>