<script setup>
import { Head, useForm, router } from '@inertiajs/vue3';
import MainLayout from '@/Layouts/MainLayout.vue';
import { wTrans } from 'laravel-vue-i18n';
import { computed, ref } from 'vue';

const props = defineProps({
    items: Array, // Now contains exploded items with unique 'id'
});

const t = wTrans;

// Initialize form using the unique ID generated by backend
const form = useForm({
    appointments: props.items.reduce((acc, item) => {
        // Initialize participants if needed
        const isMulti = ['couple', 'group', 'family'].includes(item.service.type);
        
        acc[item.id] = {
            cart_item_id: item.cart_item_id,
            service_title: item.title,
            service_type: item.service.type, // Store type to use in template
            date: '',
            time: '',
            notes: '',
            pending: false, // Feature: "Dejar abierta"
            participants: isMulti ? [{ name: '', surname: '', gender: '', custom_gender: '' }] : [],
        };
        return acc;
    }, {})
});

const availableTimes = ['09:00', '10:00', '11:00', '12:00', '14:00', '15:00', '16:00', '17:00'];

const submit = () => {
    form.post(route('scheduling.store'), {
        onSuccess: () => {
            // Redirect to checkout
        }
    });
};

const isFormValid = computed(() => {
    return Object.values(form.appointments).every(a => {
        // Check core date/time (unless pending)
        const dateValid = a.pending || (a.date && a.time);
        
        // Check participants if applicable
        const participantsValid = a.participants.length === 0 || a.participants.every(p => p.name && p.surname && p.gender);
        
        return dateValid && participantsValid;
    });
});

const togglePending = (id) => {
    if (form.appointments[id].pending) {
        form.appointments[id].date = '';
        form.appointments[id].time = '';
    }
};

const addParticipant = (id) => {
    form.appointments[id].participants.push({ name: '', surname: '', gender: '', custom_gender: '' });
};

const removeParticipant = (id, index) => {
    form.appointments[id].participants.splice(index, 1);
};
</script>

<template>
    <Head title="Agendar Citas" />
    <MainLayout>
        <div class="py-12 bg-gray-50 dark:bg-secondary-900 min-h-screen">
            <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                <h1 class="text-3xl font-bold text-secondary-900 dark:text-white mb-8">Agendar Sesiones</h1>

                <div class="bg-white dark:bg-secondary-800 rounded-xl shadow-lg p-6">
                    <p class="mb-6 text-secondary-600 dark:text-secondary-400">
                        Selecciona fecha y hora para tus sesiones. Puedes optar por dejar la fecha abierta y agendar después.
                    </p>

                    <form @submit.prevent="submit" class="space-y-8">
                        <div v-for="item in items" :key="item.id" class="border-b border-gray-200 dark:border-secondary-700 pb-8 last:border-0 last:pb-0">
                            <h3 class="text-xl font-semibold text-primary-700 dark:text-primary-300 mb-4">
                                {{ item.title }}
                            </h3>

                            <div class="mb-4">
                                <label class="inline-flex items-center cursor-pointer">
                                    <input type="checkbox" v-model="form.appointments[item.id].pending" @change="togglePending(item.id)" class="rounded border-gray-300 text-primary-600 shadow-sm focus:border-primary-300 focus:ring focus:ring-primary-200 focus:ring-opacity-50">
                                    <span class="ml-2 text-secondary-700 dark:text-secondary-300">Dejar fecha abierta (Agendar después)</span>
                                </label>
                            </div>

                            <div v-if="!form.appointments[item.id].pending" class="grid grid-cols-1 md:grid-cols-2 gap-6 transition-all duration-300">
                                <div>
                                    <label class="block text-sm font-medium text-secondary-700 dark:text-secondary-300 mb-1">Fecha</label>
                                    <input type="date" v-model="form.appointments[item.id].date" class="w-full rounded-lg border-gray-300 dark:border-secondary-600 dark:bg-secondary-700 focus:ring-primary-500 focus:border-primary-500" required :min="new Date().toISOString().split('T')[0]" />
                                </div>
                                <div>
                                    <label class="block text-sm font-medium text-secondary-700 dark:text-secondary-300 mb-1">Hora</label>
                                    <select v-model="form.appointments[item.id].time" class="w-full rounded-lg border-gray-300 dark:border-secondary-600 dark:bg-secondary-700 focus:ring-primary-500 focus:border-primary-500" required>
                                        <option value="" disabled>Seleccionar hora</option>
                                        <option v-for="time in availableTimes" :key="time" :value="time">{{ time }}</option>
                                    </select>
                                </div>
                            </div>
                            <div v-else class="text-sm text-yellow-600 dark:text-yellow-400 bg-yellow-50 dark:bg-yellow-900/20 p-3 rounded-lg">
                                Esta sesión quedará pendiente. Podrás agendarla más tarde desde tu perfil o contactando a soporte.
                            </div>

                            <!-- Participants Section -->
                            <div v-if="['couple', 'group', 'family'].includes(item.service.type)" class="mt-6 space-y-4">
                                <div class="flex items-center justify-between">
                                    <h4 class="text-md font-medium text-secondary-900 dark:text-white">{{ t('booking.participants') || 'Participantes Adicionales' }}</h4>
                                    <button type="button" @click="addParticipant(item.id)" class="text-sm text-primary-600 hover:text-primary-700 font-medium flex items-center">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                                        </svg>
                                        {{ t('booking.add_participant') || 'Agregar' }}
                                    </button>
                                </div>

                                <div v-for="(participant, index) in form.appointments[item.id].participants" :key="index" class="bg-gray-50 dark:bg-secondary-700/50 p-4 rounded-lg border border-gray-100 dark:border-secondary-700 relative">
                                    <button  type="button" @click="removeParticipant(item.id, index)" class="absolute top-2 right-2 text-red-500 hover:text-red-700">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                        </svg>
                                    </button>
                                    
                                    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                                        <div>
                                            <label class="block text-xs font-medium text-secondary-700 dark:text-secondary-300 mb-1">{{ t('booking.name') }}</label>
                                            <input v-model="participant.name" type="text" placholder="Nombre" required class="w-full text-sm rounded-lg border-secondary-300 dark:border-secondary-600 dark:bg-secondary-700 dark:text-white focus:border-primary-500 focus:ring-primary-500" />
                                        </div>
                                        <div>
                                            <label class="block text-xs font-medium text-secondary-700 dark:text-secondary-300 mb-1">{{ t('booking.surname') }}</label>
                                            <input v-model="participant.surname" type="text" placeholder="Apellidos" required class="w-full text-sm rounded-lg border-secondary-300 dark:border-secondary-600 dark:bg-secondary-700 dark:text-white focus:border-primary-500 focus:ring-primary-500" />
                                        </div>
                                        <div>
                                            <label class="block text-xs font-medium text-secondary-700 dark:text-secondary-300 mb-1">{{ t('booking.gender') }}</label>
                                            <select v-model="participant.gender" required class="w-full text-sm rounded-lg border-secondary-300 dark:border-secondary-600 dark:bg-secondary-700 dark:text-white focus:border-primary-500 focus:ring-primary-500">
                                                <option value="">{{ t('booking.select_gender') || 'Seleccionar' }}</option>
                                                <option value="male">{{ t('booking.male') }}</option>
                                                <option value="female">{{ t('booking.female') }}</option>
                                                <option value="non_binary">{{ t('booking.non_binary') }}</option>
                                                <option value="other">{{ t('booking.other') }}</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="flex justify-end pt-6">
                            <button type="submit" :disabled="form.processing || !isFormValid" class="px-8 py-3 bg-primary-600 text-white rounded-lg font-bold hover:bg-primary-700 transition shadow-lg disabled:opacity-50 disabled:cursor-not-allowed">
                                Continuar al Pago
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </MainLayout>
</template>
